### ISSUE TITLE
Findprotobuf.cmake not found

### ISSUE THREAD

**Issue by Patterner** [AutoFFI/AutoFFI#14]
1> locate -i findprotobuf.cmake
/usr/share/cmake-3.7/Modules/FindProtobuf.cmake

1> cmake --version
cmake version 3.7.2

```
@ CMakeLists.txt:36 @ find_package(Clang REQUIRED)
if (USE_LOCAL_PROTOBUF)
  add_subdirectory(vendor/protobuf/cmake)
else()
-  find_package(protobuf REQUIRED)
+  find_package(Protobuf REQUIRED)
endif()
if (USE_LOCAL_BOOST)
  link_directories(vendor/boost/out/lib)
```

And since ```cmake``` is an Abomination Upon Nuggan and refuses to use Boost i'm out.

**Comment by samvv** [comment]
Thank you for reporting this issue. Admittedly, CMake is not the prettiest of software packages out there (and that's an understatement), but it was the one I was most familiar with. Linux is not well supported at the moment, but I'll make sure I get a smoothly working version by the end of this weekend.

**Comment by samvv** [comment]
@Patterner Sorry for the late answer, but building should now work immediately on newer Linux systems. The [build instructions](https://github.com/AutoFFI/AutoFFI/blob/master/BUILDING.md). I'll close this issue for now, but should you still be interested in this project, feel free to re-open this issue if you encounter any problems.
