### ISSUE TITLE
Brew Cask Broken

### ISSUE THREAD

**Issue by colindunn** [AutoFFI/AutoFFI#2]
Hi there,

Your brew casks is currently broken for this package because there are no longer any releases in this github repository.
https://github.com/caskroom/homebrew-cask/Casks/autoffi.rb

Do you want to the cask to continue or be removed? Can you advice?

Cheers

**Comment by samvv** [comment]
Hi,

Missed your issue, sorry. Thanks for notifying, I preferably don't have it removed. I'll fix it now.

**Comment by samvv** [comment]
Fixed it by creating an own tap. AutoFFI/homebrew-autoffi.
